### ISSUE TITLE
add overlay never shows

### ISSUE THREAD

**Issue by 2xAA** [kormyen/memex#10]
"add" seems broken, clicking on it removes the masonry layout but doesn't show the form input.

**Comment by kormyen** [comment]
I've removed the electron aspect / add stuffs. Sorry for the hassles @2xAA ! T_T

I've just found myself not using it at all and have other priorities atm (though not against it existing). Since the database is entirely text and human readable its very easy and fast to just add content via text editor.

**Comment by 2xAA** [comment]
Ah no worries! Thanks for looking at this :)
